/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminportalRouteImport } from './routes/adminportal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFacultyRouteRouteImport } from './routes/_authenticated/faculty/route'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedMarksRouteImport } from './routes/_authenticated/marks'
import { Route as AuthenticatedNoticesRouteImport } from './routes/_authenticated/notices'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSubjectsRouteImport } from './routes/_authenticated/subjects'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin/branches'
import { Route as AuthenticatedAdminFacultyRouteImport } from './routes/_authenticated/admin/faculty'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminSubjectsRouteImport } from './routes/_authenticated/admin/subjects'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AuthenticatedAdminTasksRouteImport } from './routes/_authenticated/admin/tasks'
import { Route as AuthenticatedAdminTelegramRouteImport } from './routes/_authenticated/admin/telegram'
import { Route as AuthenticatedAdminTwilioRouteImport } from './routes/_authenticated/admin/twilio'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedFacultyIndexRouteImport } from './routes/_authenticated/faculty/index'
import { Route as AuthenticatedFacultyAnnouncementsRouteImport } from './routes/_authenticated/faculty/announcements'
import { Route as AuthenticatedFacultyDeadlinesRouteImport } from './routes/_authenticated/faculty/deadlines'
import { Route as ApiPublicHooksAisensyRemindersRouteImport } from './routes/api/public/hooks/aisensy-reminders'
import { Route as ApiPublicHooksAisensyWebhookRouteImport } from './routes/api/public/hooks/aisensy-webhook'
import { Route as ApiPublicHooksTelegramRemindersRouteImport } from './routes/api/public/hooks/telegram-reminders'
import { Route as ApiPublicHooksTelegramWebhookRouteImport } from './routes/api/public/hooks/telegram-webhook'
import { Route as ApiPublicHooksTwilioRemindersRouteImport } from './routes/api/public/hooks/twilio-reminders'
import { Route as ApiPublicHooksTwilioWebhookRouteImport } from './routes/api/public/hooks/twilio-webhook'
import { Route as ApiPublicHooksWeeklyDigestRouteImport } from './routes/api/public/hooks/weekly-digest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminportalRoute = AdminportalRouteImport.update({
  id: '/adminportal',
  path: '/adminportal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacultyRouteRoute =
  AuthenticatedFacultyRouteRouteImport.update({
    id: '/faculty',
    path: '/faculty',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarksRoute = AuthenticatedMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNoticesRoute = AuthenticatedNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubjectsRoute = AuthenticatedSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFacultyRoute =
  AuthenticatedAdminFacultyRouteImport.update({
    id: '/faculty',
    path: '/faculty',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSubjectsRoute =
  AuthenticatedAdminSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTasksRoute = AuthenticatedAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTelegramRoute =
  AuthenticatedAdminTelegramRouteImport.update({
    id: '/telegram',
    path: '/telegram',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTwilioRoute =
  AuthenticatedAdminTwilioRouteImport.update({
    id: '/twilio',
    path: '/twilio',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedFacultyIndexRoute =
  AuthenticatedFacultyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFacultyRouteRoute,
  } as any)
const AuthenticatedFacultyAnnouncementsRoute =
  AuthenticatedFacultyAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedFacultyRouteRoute,
  } as any)
const AuthenticatedFacultyDeadlinesRoute =
  AuthenticatedFacultyDeadlinesRouteImport.update({
    id: '/deadlines',
    path: '/deadlines',
    getParentRoute: () => AuthenticatedFacultyRouteRoute,
  } as any)
const ApiPublicHooksAisensyRemindersRoute =
  ApiPublicHooksAisensyRemindersRouteImport.update({
    id: '/api/public/hooks/aisensy-reminders',
    path: '/api/public/hooks/aisensy-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAisensyWebhookRoute =
  ApiPublicHooksAisensyWebhookRouteImport.update({
    id: '/api/public/hooks/aisensy-webhook',
    path: '/api/public/hooks/aisensy-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelegramRemindersRoute =
  ApiPublicHooksTelegramRemindersRouteImport.update({
    id: '/api/public/hooks/telegram-reminders',
    path: '/api/public/hooks/telegram-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelegramWebhookRoute =
  ApiPublicHooksTelegramWebhookRouteImport.update({
    id: '/api/public/hooks/telegram-webhook',
    path: '/api/public/hooks/telegram-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTwilioRemindersRoute =
  ApiPublicHooksTwilioRemindersRouteImport.update({
    id: '/api/public/hooks/twilio-reminders',
    path: '/api/public/hooks/twilio-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTwilioWebhookRoute =
  ApiPublicHooksTwilioWebhookRouteImport.update({
    id: '/api/public/hooks/twilio-webhook',
    path: '/api/public/hooks/twilio-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyDigestRoute =
  ApiPublicHooksWeeklyDigestRouteImport.update({
    id: '/api/public/hooks/weekly-digest',
    path: '/api/public/hooks/weekly-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminportal': typeof AdminportalRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/faculty': typeof AuthenticatedFacultyRouteRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/marks': typeof AuthenticatedMarksRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/faculty': typeof AuthenticatedAdminFacultyRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/admin/twilio': typeof AuthenticatedAdminTwilioRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/faculty/announcements': typeof AuthenticatedFacultyAnnouncementsRoute
  '/faculty/deadlines': typeof AuthenticatedFacultyDeadlinesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/faculty/': typeof AuthenticatedFacultyIndexRoute
  '/api/public/hooks/aisensy-reminders': typeof ApiPublicHooksAisensyRemindersRoute
  '/api/public/hooks/aisensy-webhook': typeof ApiPublicHooksAisensyWebhookRoute
  '/api/public/hooks/telegram-reminders': typeof ApiPublicHooksTelegramRemindersRoute
  '/api/public/hooks/telegram-webhook': typeof ApiPublicHooksTelegramWebhookRoute
  '/api/public/hooks/twilio-reminders': typeof ApiPublicHooksTwilioRemindersRoute
  '/api/public/hooks/twilio-webhook': typeof ApiPublicHooksTwilioWebhookRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminportal': typeof AdminportalRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/marks': typeof AuthenticatedMarksRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/faculty': typeof AuthenticatedAdminFacultyRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/admin/twilio': typeof AuthenticatedAdminTwilioRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/faculty/announcements': typeof AuthenticatedFacultyAnnouncementsRoute
  '/faculty/deadlines': typeof AuthenticatedFacultyDeadlinesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/faculty': typeof AuthenticatedFacultyIndexRoute
  '/api/public/hooks/aisensy-reminders': typeof ApiPublicHooksAisensyRemindersRoute
  '/api/public/hooks/aisensy-webhook': typeof ApiPublicHooksAisensyWebhookRoute
  '/api/public/hooks/telegram-reminders': typeof ApiPublicHooksTelegramRemindersRoute
  '/api/public/hooks/telegram-webhook': typeof ApiPublicHooksTelegramWebhookRoute
  '/api/public/hooks/twilio-reminders': typeof ApiPublicHooksTwilioRemindersRoute
  '/api/public/hooks/twilio-webhook': typeof ApiPublicHooksTwilioWebhookRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/adminportal': typeof AdminportalRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/faculty': typeof AuthenticatedFacultyRouteRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/marks': typeof AuthenticatedMarksRoute
  '/_authenticated/notices': typeof AuthenticatedNoticesRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/subjects': typeof AuthenticatedSubjectsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/faculty': typeof AuthenticatedAdminFacultyRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/_authenticated/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/_authenticated/admin/twilio': typeof AuthenticatedAdminTwilioRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/faculty/announcements': typeof AuthenticatedFacultyAnnouncementsRoute
  '/_authenticated/faculty/deadlines': typeof AuthenticatedFacultyDeadlinesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/faculty/': typeof AuthenticatedFacultyIndexRoute
  '/api/public/hooks/aisensy-reminders': typeof ApiPublicHooksAisensyRemindersRoute
  '/api/public/hooks/aisensy-webhook': typeof ApiPublicHooksAisensyWebhookRoute
  '/api/public/hooks/telegram-reminders': typeof ApiPublicHooksTelegramRemindersRoute
  '/api/public/hooks/telegram-webhook': typeof ApiPublicHooksTelegramWebhookRoute
  '/api/public/hooks/twilio-reminders': typeof ApiPublicHooksTwilioRemindersRoute
  '/api/public/hooks/twilio-webhook': typeof ApiPublicHooksTwilioWebhookRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminportal'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/faculty'
    | '/analytics'
    | '/assistant'
    | '/dashboard'
    | '/groups'
    | '/marks'
    | '/notices'
    | '/planner'
    | '/profile'
    | '/subjects'
    | '/tasks'
    | '/timeline'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/branches'
    | '/admin/faculty'
    | '/admin/notifications'
    | '/admin/subjects'
    | '/admin/support'
    | '/admin/tasks'
    | '/admin/telegram'
    | '/admin/twilio'
    | '/admin/users'
    | '/faculty/announcements'
    | '/faculty/deadlines'
    | '/admin/'
    | '/faculty/'
    | '/api/public/hooks/aisensy-reminders'
    | '/api/public/hooks/aisensy-webhook'
    | '/api/public/hooks/telegram-reminders'
    | '/api/public/hooks/telegram-webhook'
    | '/api/public/hooks/twilio-reminders'
    | '/api/public/hooks/twilio-webhook'
    | '/api/public/hooks/weekly-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminportal'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/assistant'
    | '/dashboard'
    | '/groups'
    | '/marks'
    | '/notices'
    | '/planner'
    | '/profile'
    | '/subjects'
    | '/tasks'
    | '/timeline'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/branches'
    | '/admin/faculty'
    | '/admin/notifications'
    | '/admin/subjects'
    | '/admin/support'
    | '/admin/tasks'
    | '/admin/telegram'
    | '/admin/twilio'
    | '/admin/users'
    | '/faculty/announcements'
    | '/faculty/deadlines'
    | '/admin'
    | '/faculty'
    | '/api/public/hooks/aisensy-reminders'
    | '/api/public/hooks/aisensy-webhook'
    | '/api/public/hooks/telegram-reminders'
    | '/api/public/hooks/telegram-webhook'
    | '/api/public/hooks/twilio-reminders'
    | '/api/public/hooks/twilio-webhook'
    | '/api/public/hooks/weekly-digest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/adminportal'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/faculty'
    | '/_authenticated/analytics'
    | '/_authenticated/assistant'
    | '/_authenticated/dashboard'
    | '/_authenticated/groups'
    | '/_authenticated/marks'
    | '/_authenticated/notices'
    | '/_authenticated/planner'
    | '/_authenticated/profile'
    | '/_authenticated/subjects'
    | '/_authenticated/tasks'
    | '/_authenticated/timeline'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/faculty'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/subjects'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/tasks'
    | '/_authenticated/admin/telegram'
    | '/_authenticated/admin/twilio'
    | '/_authenticated/admin/users'
    | '/_authenticated/faculty/announcements'
    | '/_authenticated/faculty/deadlines'
    | '/_authenticated/admin/'
    | '/_authenticated/faculty/'
    | '/api/public/hooks/aisensy-reminders'
    | '/api/public/hooks/aisensy-webhook'
    | '/api/public/hooks/telegram-reminders'
    | '/api/public/hooks/telegram-webhook'
    | '/api/public/hooks/twilio-reminders'
    | '/api/public/hooks/twilio-webhook'
    | '/api/public/hooks/weekly-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminportalRoute: typeof AdminportalRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksAisensyRemindersRoute: typeof ApiPublicHooksAisensyRemindersRoute
  ApiPublicHooksAisensyWebhookRoute: typeof ApiPublicHooksAisensyWebhookRoute
  ApiPublicHooksTelegramRemindersRoute: typeof ApiPublicHooksTelegramRemindersRoute
  ApiPublicHooksTelegramWebhookRoute: typeof ApiPublicHooksTelegramWebhookRoute
  ApiPublicHooksTwilioRemindersRoute: typeof ApiPublicHooksTwilioRemindersRoute
  ApiPublicHooksTwilioWebhookRoute: typeof ApiPublicHooksTwilioWebhookRoute
  ApiPublicHooksWeeklyDigestRoute: typeof ApiPublicHooksWeeklyDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminportal': {
      id: '/adminportal'
      path: '/adminportal'
      fullPath: '/adminportal'
      preLoaderRoute: typeof AdminportalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faculty': {
      id: '/_authenticated/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof AuthenticatedFacultyRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marks': {
      id: '/_authenticated/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof AuthenticatedMarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notices': {
      id: '/_authenticated/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AuthenticatedNoticesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects': {
      id: '/_authenticated/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/faculty': {
      id: '/_authenticated/admin/faculty'
      path: '/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AuthenticatedAdminFacultyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/subjects': {
      id: '/_authenticated/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tasks': {
      id: '/_authenticated/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AuthenticatedAdminTasksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/telegram': {
      id: '/_authenticated/admin/telegram'
      path: '/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AuthenticatedAdminTelegramRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/twilio': {
      id: '/_authenticated/admin/twilio'
      path: '/twilio'
      fullPath: '/admin/twilio'
      preLoaderRoute: typeof AuthenticatedAdminTwilioRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/faculty/': {
      id: '/_authenticated/faculty/'
      path: '/'
      fullPath: '/faculty/'
      preLoaderRoute: typeof AuthenticatedFacultyIndexRouteImport
      parentRoute: typeof AuthenticatedFacultyRouteRoute
    }
    '/_authenticated/faculty/announcements': {
      id: '/_authenticated/faculty/announcements'
      path: '/announcements'
      fullPath: '/faculty/announcements'
      preLoaderRoute: typeof AuthenticatedFacultyAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedFacultyRouteRoute
    }
    '/_authenticated/faculty/deadlines': {
      id: '/_authenticated/faculty/deadlines'
      path: '/deadlines'
      fullPath: '/faculty/deadlines'
      preLoaderRoute: typeof AuthenticatedFacultyDeadlinesRouteImport
      parentRoute: typeof AuthenticatedFacultyRouteRoute
    }
    '/api/public/hooks/aisensy-reminders': {
      id: '/api/public/hooks/aisensy-reminders'
      path: '/api/public/hooks/aisensy-reminders'
      fullPath: '/api/public/hooks/aisensy-reminders'
      preLoaderRoute: typeof ApiPublicHooksAisensyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/aisensy-webhook': {
      id: '/api/public/hooks/aisensy-webhook'
      path: '/api/public/hooks/aisensy-webhook'
      fullPath: '/api/public/hooks/aisensy-webhook'
      preLoaderRoute: typeof ApiPublicHooksAisensyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-reminders': {
      id: '/api/public/hooks/telegram-reminders'
      path: '/api/public/hooks/telegram-reminders'
      fullPath: '/api/public/hooks/telegram-reminders'
      preLoaderRoute: typeof ApiPublicHooksTelegramRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-webhook': {
      id: '/api/public/hooks/telegram-webhook'
      path: '/api/public/hooks/telegram-webhook'
      fullPath: '/api/public/hooks/telegram-webhook'
      preLoaderRoute: typeof ApiPublicHooksTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/twilio-reminders': {
      id: '/api/public/hooks/twilio-reminders'
      path: '/api/public/hooks/twilio-reminders'
      fullPath: '/api/public/hooks/twilio-reminders'
      preLoaderRoute: typeof ApiPublicHooksTwilioRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/twilio-webhook': {
      id: '/api/public/hooks/twilio-webhook'
      path: '/api/public/hooks/twilio-webhook'
      fullPath: '/api/public/hooks/twilio-webhook'
      preLoaderRoute: typeof ApiPublicHooksTwilioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-digest': {
      id: '/api/public/hooks/weekly-digest'
      path: '/api/public/hooks/weekly-digest'
      fullPath: '/api/public/hooks/weekly-digest'
      preLoaderRoute: typeof ApiPublicHooksWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminFacultyRoute: typeof AuthenticatedAdminFacultyRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminSubjectsRoute: typeof AuthenticatedAdminSubjectsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminTasksRoute: typeof AuthenticatedAdminTasksRoute
  AuthenticatedAdminTelegramRoute: typeof AuthenticatedAdminTelegramRoute
  AuthenticatedAdminTwilioRoute: typeof AuthenticatedAdminTwilioRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
    AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
    AuthenticatedAdminFacultyRoute: AuthenticatedAdminFacultyRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminSubjectsRoute: AuthenticatedAdminSubjectsRoute,
    AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
    AuthenticatedAdminTasksRoute: AuthenticatedAdminTasksRoute,
    AuthenticatedAdminTelegramRoute: AuthenticatedAdminTelegramRoute,
    AuthenticatedAdminTwilioRoute: AuthenticatedAdminTwilioRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedFacultyRouteRouteChildren {
  AuthenticatedFacultyAnnouncementsRoute: typeof AuthenticatedFacultyAnnouncementsRoute
  AuthenticatedFacultyDeadlinesRoute: typeof AuthenticatedFacultyDeadlinesRoute
  AuthenticatedFacultyIndexRoute: typeof AuthenticatedFacultyIndexRoute
}

const AuthenticatedFacultyRouteRouteChildren: AuthenticatedFacultyRouteRouteChildren =
  {
    AuthenticatedFacultyAnnouncementsRoute:
      AuthenticatedFacultyAnnouncementsRoute,
    AuthenticatedFacultyDeadlinesRoute: AuthenticatedFacultyDeadlinesRoute,
    AuthenticatedFacultyIndexRoute: AuthenticatedFacultyIndexRoute,
  }

const AuthenticatedFacultyRouteRouteWithChildren =
  AuthenticatedFacultyRouteRoute._addFileChildren(
    AuthenticatedFacultyRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedFacultyRouteRoute: typeof AuthenticatedFacultyRouteRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedMarksRoute: typeof AuthenticatedMarksRoute
  AuthenticatedNoticesRoute: typeof AuthenticatedNoticesRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSubjectsRoute: typeof AuthenticatedSubjectsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedFacultyRouteRoute: AuthenticatedFacultyRouteRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedMarksRoute: AuthenticatedMarksRoute,
  AuthenticatedNoticesRoute: AuthenticatedNoticesRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSubjectsRoute: AuthenticatedSubjectsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminportalRoute: AdminportalRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksAisensyRemindersRoute: ApiPublicHooksAisensyRemindersRoute,
  ApiPublicHooksAisensyWebhookRoute: ApiPublicHooksAisensyWebhookRoute,
  ApiPublicHooksTelegramRemindersRoute: ApiPublicHooksTelegramRemindersRoute,
  ApiPublicHooksTelegramWebhookRoute: ApiPublicHooksTelegramWebhookRoute,
  ApiPublicHooksTwilioRemindersRoute: ApiPublicHooksTwilioRemindersRoute,
  ApiPublicHooksTwilioWebhookRoute: ApiPublicHooksTwilioWebhookRoute,
  ApiPublicHooksWeeklyDigestRoute: ApiPublicHooksWeeklyDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
